package org.itrunner.heroes.dto;

public class HeroDTO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero.id
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hero.name
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero.id
     *
     * @return the value of hero.id
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero.id
     *
     * @param id the value for hero.id
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hero.name
     *
     * @return the value of hero.name
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    public String getName() {
        return name != null?name.trim():null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hero.name
     *
     * @param name the value for hero.name
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    public void setName(String name) {
        this.name = name;
    }
}