package org.itrunner.heroes.dto;

import java.util.Date;

public class UsersDTO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.id
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.email
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.enabled
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.lastpasswordresetdate
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    private Date lastpasswordresetdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.username
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.id
     *
     * @return the value of users.id
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.id
     *
     * @param id the value for users.id
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.email
     *
     * @return the value of users.email
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    public String getEmail() {
        return email != null?email.trim():null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.email
     *
     * @param email the value for users.email
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.enabled
     *
     * @return the value of users.enabled
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.enabled
     *
     * @param enabled the value for users.enabled
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.lastpasswordresetdate
     *
     * @return the value of users.lastpasswordresetdate
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    public Date getLastpasswordresetdate() {
        return lastpasswordresetdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.lastpasswordresetdate
     *
     * @param lastpasswordresetdate the value for users.lastpasswordresetdate
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    public void setLastpasswordresetdate(Date lastpasswordresetdate) {
        this.lastpasswordresetdate = lastpasswordresetdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password
     *
     * @return the value of users.password
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    public String getPassword() {
        return password != null?password.trim():null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password
     *
     * @param password the value for users.password
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.username
     *
     * @return the value of users.username
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    public String getUsername() {
        return username != null?username.trim():null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.username
     *
     * @param username the value for users.username
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }
}