package org.itrunner.heroes.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.itrunner.heroes.dto.AuthorityCriteria;
import org.itrunner.heroes.dto.AuthorityDTO;
import org.itrunner.heroes.model.Authority;
import org.springframework.stereotype.Repository;
@Repository
public interface AuthorityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    int countByCriteria(AuthorityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    int deleteByCriteria(AuthorityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    int insert(AuthorityDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    int insertSelective(AuthorityDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    List<AuthorityDTO> selectByCriteria(AuthorityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    AuthorityDTO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    int updateByCriteriaSelective(@Param("record") AuthorityDTO record, @Param("example") AuthorityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    int updateByCriteria(@Param("record") AuthorityDTO record, @Param("example") AuthorityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    int updateByPrimaryKeySelective(AuthorityDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authority
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    int updateByPrimaryKey(AuthorityDTO record);

	List<AuthorityDTO> getAuthorites(@Param("userId") Long userId);
}