package org.itrunner.heroes.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.itrunner.heroes.dto.HeroCriteria;
import org.itrunner.heroes.dto.HeroDTO;
import org.springframework.stereotype.Repository;
@Repository
public interface HeroDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    int countByCriteria(HeroCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    int deleteByCriteria(HeroCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    int insert(HeroDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    int insertSelective(HeroDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    List<HeroDTO> selectByCriteria(HeroCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    HeroDTO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    int updateByCriteriaSelective(@Param("record") HeroDTO record, @Param("example") HeroCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    int updateByCriteria(@Param("record") HeroDTO record, @Param("example") HeroCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    int updateByPrimaryKeySelective(HeroDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hero
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    int updateByPrimaryKey(HeroDTO record);
}