package org.itrunner.heroes.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.itrunner.heroes.dto.UserAuthorityCriteria;
import org.itrunner.heroes.dto.UserAuthorityDTO;
import org.springframework.stereotype.Repository;
@Repository
public interface UserAuthorityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authority
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    int countByCriteria(UserAuthorityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authority
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    int deleteByCriteria(UserAuthorityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authority
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    int insert(UserAuthorityDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authority
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    int insertSelective(UserAuthorityDTO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authority
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    List<UserAuthorityDTO> selectByCriteria(UserAuthorityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authority
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    int updateByCriteriaSelective(@Param("record") UserAuthorityDTO record, @Param("example") UserAuthorityCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_authority
     *
     * @mbggenerated Thu Nov 01 23:33:33 CDT 2018
     */
    int updateByCriteria(@Param("record") UserAuthorityDTO record, @Param("example") UserAuthorityCriteria example);
}